# General {{{
unbind C-b
set-option -g prefix C-t

set -g mouse on
setw -g mode-keys vi

# bind C-e send-prefix
bind ` last-window

# Length of the history
set -g history-limit 100000

# Use xterm-256color
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

# Suppose to decrease lag
set-option -s escape-time 10
set-option -g allow-passthrough on
set-option -g detach-on-destroy off
set-option -ga update-environment TERM
set-option -ga update-environment TERM_PROGRAM

# }}}

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'

set -g @catppuccin_flavour "mocha" # or frappe, macchiato, mocha
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

set -g status-position top
set -g status-justify "left"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"

set -g status-left-length 0
set -g status-left ""

set -g status-right-length 100
set -g status-right "#[fg=#{@thm_blue}]#{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-right "#[fg=#{@thm_fg} bold](#S)"
set -ga status-right "#{?client_prefix,#[fg=#{@thm_bg} bg=#{@thm_red} bold] PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold] NORMAL }}"

setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-active-border-style "fg=#{@thm_sky}"
setw -g pane-border-style "fg=#{@thm_surface_0}"
setw -g pane-border-lines single

# Binding {{{

bind-key r source-file ~/.config/tmux/.tmux.conf \; display-message "tmux.conf reloaded"

# Switch panes
unbind h
unbind l
unbind j
unbind k
bind h select-pane -L
bind l select-pane -R
bind j select-pane -U
bind k select-pane -D

# Resize pane
bind-key -r H resize-pane -L
bind-key -r J resize-pane -D
bind-key -r K resize-pane -U
bind-key -r L resize-pane -R

# Toogle pane zoom
unbind m
bind m resize-pane -Z

# New pane/window with cwd
bind - split-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# }}}

# set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"
# run '~/.tmux/plugins/tpm/tpm'
run '/opt/homebrew/opt/tpm/share/tpm/tpm'
